### ISSUE TITLE
Re-enable the ability to explicitly set the 'nullok' option

### ISSUE THREAD

**Issue by michael-riddle** [simp/pupmod-simp-pam#124]
I can understand why completely removing support for the nullok option was removed, but I don't believe we should completely take the option of configuring an option away from a user just because their misconfiguration of it could lead to insecurity.

**Comment by op-ct** [comment]
(For anyone else who doesn't remember when/why nullok was removed, it was prior to the initial open source release, in 2011: https://github.com/simp/pupmod-simp-pam/blob/master/CHANGELOG#L327-L335)
